name: Ping Dishes Endpoint

on:
    schedule:
        - cron: "*/10 * * * *" # Every 10 minutes
    workflow_dispatch: # So you can also trigger it manually

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Curl your endpoint
              run: |
                  curl -X GET https://taste-eat.onrender.com/api/dishes
